name: Test Custom Actions

on: [push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Use Custom Action from Action Library
      uses: xaxay/action_library/.github/actions/tag-new-version@main
      with:
        some-input: value
      env:
        GITHUB_TOKEN: ${{ secrets.REPO_SECRET }}
